### ISSUE TITLE
selecting "bulleted list" or "numbered list" causes new lines being created in race condition

### ISSUE THREAD

**Issue by Shaolin69** [Backendless/ui-builder-library#443]
To reproduce, type some things in the editor... then select "bulleted list" in toolbar to start a list. Editor suddenly grows vertically and keeps expanding infinitely...

**Comment by stanislav-grin** [comment]
Hello @Shaolin69,

thank you for reporting this issue.
I have created an internal ticket for this issue (BKNDLSS-32038). Our engineer will fix it asap.

**Comment by snaqqqystas** [comment]
Hi, @Shaolin69, we can't reproduce your bug, but our team were fixed the possible cause of bug. The updated version is already on the marketplace. You can install the latest component version and try again, and if it's ok - good) if not - give us steps to reproduce, please, or screencast (if it is possible).
