### ISSUE TITLE
data binding causes loss of focus

### ISSUE THREAD

**Issue by Shaolin69** [Backendless/ui-builder-library#458]
When setting a data binding property in "content" for this component, the user can only type one letter... as soon as he does, focus is lost and user has to click into the input field to type the second letter... and then focus is lost again... this bug only happens when doing data binding in UI Builder.

**Comment by stanislav-grin** [comment]
Hello @Shaolin69,
an internal ticket was created to fix this issue, it's already in progress.

**Comment by snaqqqystas** [comment]
Hi, @Shaolin69, the bug has been fixed, you can check it after installation the latest component version - Rich Editor (v1.3.0)

**Comment by Shaolin69** [comment]
This bug is fixed but yet another bug has appeared... will make new issue
