### ISSUE TITLE
bl-popover-component: position property not working

### ISSUE THREAD

**Issue by Shaolin69** [Backendless/ui-builder-library#463]
The popover content is positioned "right" no matter what is selected in the options.

**Comment by snaqqqystas** [comment]
Hi, @Shaolin69, our team already work on this task, thanks! 
We'll notify you, when it's fixed.

**Comment by Shaolin69** [comment]
Seems to work fine now 😀

**Comment by snaqqqystas** [comment]
ok, thank you!
