### ISSUE TITLE
README.MD Incorrect

### ISSUE THREAD

**Issue by howardjacobson** [Backendless/ui-builder-library#504]
The README.MD instructs that there is an object data model for the Tab component that has a currentTabID property.  In the Backendless UI, I do not see a data model for the Tab component.  I see two actions in the Logic tab of UI Builder, one of which is "Get Current Tab ID", but that action returns "null", which does not make sense.

Is the documentation out of date?

**Comment by snaqqqystas** [comment]
Hi, Howard, thank for your ticket! Our team will check this issue, and we'll notified you about results.

**Comment by snaqqqystas** [comment]
@howardjacobson, we can't reproduce your bug, can you share to us your steps, please? in text or video

**Comment by howardjacobson** [comment]
Hello.

I figured out my error.  I did not have the tab blocks inside the Tab component.  That requirement isn't clear from the documentation, but I see it now.  Thanks for your help.  I'd suggest adding this to the README at the step where the tab blocks are added:

"Note:  Be sure to place the tab blocks for Tab1, Tab2, and Tab3 INSIDE the Tabs component.  The Tabs component uses the Backendless POD feature, which requires proper nesting of UI components."

**Comment by snaqqqystas** [comment]
Thank you, we are working on this!

**Comment by snaqqqystas** [comment]
Hello, @howardjacobson, we have fixed the Readme, according your comment.
You can check it [HERE](https://github.com/Backendless/ui-builder-library/blob/main/components/bl-tabs-component/README.md).
Thank for your participation in improving our product!
